services:
  db:
    container_name: ss-postgres
    image: postgres:16.3
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ss-network

volumes:
  postgres_data:

networks:
  ss-network:
    driver: bridge
    external: true
