services:
  ss-admin:
    container_name: ss-admin
    build:
      context: ../../
    volumes:
      - ./src:/app/src
    ports:
      - ${SS_ADMIN_PORT}:${SS_ADMIN_PORT}
    # restart: always
    env_file:
      - .env
    networks:
      - ss-network

  db:
    container_name: ss-postgres
    image: postgres:16.3
    # restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ss-network

volumes:
  postgres_data:

networks:
  ss-network:
    driver: bridge
    external: true
